version: '2'
services:
    php:
        build: ./php-fpm
        container_name: php_symfony_project
        volumes:
            - ./symfony_project:/var/www/symfony_project
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
    web:
        image: nginx:latest
        container_name: nginx_symfony
        ports:
            - "80:80"
        volumes:
            - ./symfony_project:/var/www/symfony_project
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    mysql:
        image: mysql:5.6
        container_name: mysql_symfony
        volumes:
          - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: symf0ny
        ports:
            - "3333:3306"
    adminer:
      image: adminer
      container_name: adminer_symfony
      restart: always
      ports:
        - 8085:8080
      links:
        - mysql:db
volumes:
  mysql:
